POST /api/usuarios HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "nombre": "Edwin",
  "apellidoP": "Vazquez",
  "apellidoM": "Hernandez",
  "fechaN": "02/04/2000",
  "tituloMEstudios": "www.titulo.com",
  "trabajoA": "",
  "proyectoP": "www.proyecto.com",
  "publicaciones": "www.publicaciones.com",
  "imagen": "imagen"
}

###
GET /api/usuarios/647409d0daf9257ada789be8 HTTP/1.1
Host: localhost:3000
Content-Type: application/json